# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0004_club_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
