# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0005_auto_20181103_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('date', models.CharField(max_length=1000)),
                ('photos', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Marathon',
        ),
    ]
