# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0007_auto_20181103_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscriptions',
            field=models.ManyToManyField(default=None, null=True, to='decathlon.Event'),
        ),
    ]
