# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0008_customer_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='decathlon.Event'),
        ),
    ]
