# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
