# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0011_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='docoins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='docoins',
            field=models.IntegerField(default=0),
        ),
    ]
