# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0012_auto_20181103_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='clubs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decathlon.Club'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photos',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decathlon.Product'),
        ),
    ]
