# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0013_auto_20181103_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='subscriber',
            field=models.ManyToManyField(to='decathlon.Customer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photos',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
