# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0014_auto_20181103_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
