# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0015_auto_20181103_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='clubs',
        ),
        migrations.AddField(
            model_name='customer',
            name='clubs',
            field=models.ManyToManyField(blank=True, null=True, to='decathlon.Club'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='decathlon.Product'),
        ),
    ]
