# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0016_auto_20181103_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='decocoins',
            field=models.IntegerField(default=200),
        ),
    ]
