# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0017_club_decocoins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite',
        ),
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to='decathlon.Product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='decathlon.Product'),
        ),
    ]
