# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0018_auto_20181104_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
