# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0019_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='subscriber',
            field=models.ManyToManyField(blank=True, null=True, to='decathlon.Customer'),
        ),
    ]
