# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0020_auto_20181104_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_coins', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decathlon.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decathlon.Customer')),
            ],
        ),
    ]
